//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyStudioPractice
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeautyStudioEntities : DbContext
    {
        public BeautyStudioEntities()
            : base("name=BeautyStudioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Пигменты> Пигменты { get; set; }
        public virtual DbSet<Посещение> Посещение { get; set; }
        public virtual DbSet<Процедура> Процедура { get; set; }
        public virtual DbSet<Процедуры_клиента> Процедуры_клиента { get; set; }
        public virtual DbSet<Скидка> Скидка { get; set; }
        public virtual DbSet<Тип_иглы> Тип_иглы { get; set; }
        public virtual DbSet<Тип_кожи> Тип_кожи { get; set; }
        public virtual DbSet<Тип_процедуры> Тип_процедуры { get; set; }
    }
}
