//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyStudioPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Посещение
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Посещение()
        {
            this.Процедуры_клиента = new HashSet<Процедуры_клиента>();
        }
    
        public int Id_посещения { get; set; }
        public int Id_клиента { get; set; }
        public System.DateTime Дата_и_время_посещения { get; set; }
        public decimal Итоговая_цена { get; set; }
        public Nullable<int> Id_типа_иглы { get; set; }
        public string Примечание_о_посещении { get; set; }
        public Nullable<int> Id_скидки { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Скидка Скидка { get; set; }
        public virtual Тип_иглы Тип_иглы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Процедуры_клиента> Процедуры_клиента { get; set; }
    }
}
