//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyStudioPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Процедуры_клиента
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Процедуры_клиента()
        {
            this.Посещение = new HashSet<Посещение>();
        }
    
        public int Id_процедуры_клиента { get; set; }
        public int Id_процедуры { get; set; }
        public int Id_пигмента { get; set; }
        public string Примечание_о_процедуре_клиента { get; set; }
    
        public virtual Пигменты Пигменты { get; set; }
        public virtual Процедура Процедура { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Посещение> Посещение { get; set; }
    }
}
