//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyStudioPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Процедура
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Процедура()
        {
            this.Процедуры_клиента = new HashSet<Процедуры_клиента>();
        }
    
        public int Id_процедуры { get; set; }
        public string Название_процедуры { get; set; }
        public int Id_типа_процедуры { get; set; }
        public int Цена_процедуры { get; set; }
    
        public virtual Тип_процедуры Тип_процедуры { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Процедуры_клиента> Процедуры_клиента { get; set; }
    }
}
